services:
  fakesvc:
    build: .
    image: sergkondr/fakesvc:dev
    command:
      - --config
      - /app/config.yaml
    configs:
      - source: config
        target: /app/config.yaml
    ports:
      - "8080:8080"

configs:
  config:
    file: ./examples/config.yaml
