services:
  fakesvc:
    build: .
    container_name: fakesvc
    image: sergkondr/fakesvc
    command:
      - --config
      - /app/config.yaml
    configs:
      - source: config
        target: /app/config.yaml
    ports:
      - 8080:8080
    depends_on: []

configs:
  config:
    file: ./examples/config.yaml
