listen: 0.0.0.0:8080

http_endpoints:
  - name: Good endpoint
    description: Fast enough, no errors at all
    path: /good
    error_rate: 0.0
    slowness:
      min: 10ms
      p95: 50ms
      max: 100ms
  - name: Bad endpoint
    description: 30% of requests fails with 500 error
    path: /bad
    error_rate: 0.3
    slowness:
      min: 300ms
      p95: 3500ms
      max: 5s
  - name: Slow good endpoint
    description: Always slow, but no errors
    path: /slow
    error_rate: 0.0
    slowness:
      min: 1s
      p95: 5s
      max: 10s
  - path: /your-service
    error_rate: 0.5
    slowness:
      min: 1s
      p95: 5s
      max: 10s
  - name: Healthcheck
    description: Fast and reliable
    path: /healthz
    hidden: true
    do_not_log: true
    error_rate: 0.0
    slowness:
      min: 10ms
      p95: 20ms
      max: 50ms
