#@data/values
---
app: fakesvc

replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

image_name: sergkondr/fakesvc
image_version: dev
port: 8080

ingress_hostname: "fakesvc.my.lab"
